language: node_js
node_js:
- node
notifications:
  email: false
  slack:
    secure: lM8Y7VftxteRjmBYpYb2vCtMcttx7tCLkPsTOE4CBQJs81wsSQT+1BH1GjNABlwXk/0DRyUl5evCPRGXj82PqDF6qfOtgTvrk46wTScbJQmyg8bZvaypqtep26LGb2orrTkO0LSicf52fwNvcnugyDbNAiDouaBbyW5snZYU6k2/fqphgHZ1din4J8r6/9dacKOILl0LGDUoKc55PXXcEsAruWjxvxZGKlqm01RL/mq0Q8ui59WKpC56oBr7BgQZQFOCKVcLHMk4y5igPVshR6nfdeSJL2OX+C58hpFMvTQcxJd6Up5yBWb6FSs+qb7soxc/GJgSJZWlq5Dwk3NgrNjW2b7GYuoKKvdd/Cy8LMw7wpT945p8SL4PLG7uX5fE0mHuCNoaaJyMNduCIbA3XMy1DVnn2OrOwX5BzwKVpz4BuHA42B4PXQ1pUbyIvKV4qcLaUhL/nYKvKbwwTZ/GAIBMuXvKIExdHKGNgfLgfaNKp/ioJ5l2bFba+M0BfIX/ZfOY1Q3ZuOER20xDaGKDdbd/CSMA03EGGNsLM6iy1k63MpfWGTLMl3UU5RSaawKpyqO4O9H2jVUJQiA19FMKUc8hOB8pkt3hYwGCPb6tA222p/mOOhjqFDLW1l/h+s/AYZ0ErHQSzZPyWe16tEsQ0Ci4+OK/Do5joTQgEWULPB0=
